name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test || exit 1

    - name: Run Integration Tests
      run: npm run test:integration || exit 1

    - name: Ensure Docker is Installed & Running
      run: |
        if ! command -v docker &> /dev/null; then
          echo "Docker not found. Installing..."
          sudo apt update && sudo apt install -y docker.io
        fi
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Build Docker Image
      run: sudo docker build -t my-html-app .

    - name: Stop and Remove Old Containers
      run: |
        sudo docker ps -q --filter "name=my-html-container" | grep -q . && sudo docker stop my-html-container || true
        sudo docker ps -a -q --filter "name=my-html-container" | grep -q . && sudo docker rm my-html-container || true

    - name: Run New Container
      run: sudo docker run -d -p 8080:80 --name my-html-container my-html-app

    - name: Wait for Container to Initialize
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:8080; then
            echo "Server is up!"
            exit 0
          fi
          echo "Waiting for server..."
          sleep 3
        done
        echo "Server failed to start!"
        exit 1

    - name: Check Running Containers
      run: |
        sudo docker ps -a
        sudo docker logs my-html-container || true
